### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by postables** [osolmaz/bijective-mnemonics#2]
Hello, I would like to use this within one of my [projects](https://github.com/RTradeLtd/Temporal). I will most likely be writing a golang version (in which case I'm not sure if this project not having a license would effect me be able to use this idea) however in the event that that I use the javascript version, a license would absolutely be needed.

Thanks :D

**Comment by osolmaz** [comment]
Done

**Comment by postables** [comment]
Wooo! Thank you :D Would you like if I opened up a PR to merge my golang version when it's done?

**Comment by osolmaz** [comment]
Wouldn't it be better if it had its own package? I don't have experience with Go, but am assuming that's the right way. And this one isn't a proper npm package anyway.

On the other hand, this is still a work in progress. The word lists should be improved. What are you planning to use it for?
